[colors]
cursor = { text = "#665c54", cursor = "#ebdbb2" }
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83A598"
cyan = "#8EC07C"
green = "#B8BB26"
magenta = "#D3869B"
red = "#FB4934"
white = "#EBDBB2"
yellow = "#FABD2F"

[colors.normal]
black = "#1D2021"
blue = "#458588"
cyan = "#689D6A"
green = "#98971A"
magenta = "#B16286"
red = "#CC241D"
white = "#A89984"
yellow = "#D79921"

[colors.primary]
background = "#1d2021"
foreground = "#EBDBB2"

[cursor]
style = "Underline"
unfocused_hollow = false

[font]
size = 18
offset.x = 1
offset.y = 3
bold.style = "Medium"

[font.normal]
family = "Iosevka Nerd Font Propo"
style = "ExtraLight"

[general]
live_config_reload = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_title = true
option_as_alt = "Both"
